package ap.mobile.myapplication.feature.nutrition.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import ap.mobile.myapplication.feature.nutrition.data.model.FoodItem
import ap.mobile.myapplication.feature.nutrition.data.repository.GiziFirestoreRepository

data class TambahMenuState(
    val menu: String = "",
    val protein: String = "",
    val lemak: String = "",
    val karbohidrat: String = ""
)

class TambahMenuViewModel : ViewModel() {

    private val repository = GiziFirestoreRepository()

    private val _uiState = MutableStateFlow(TambahMenuState())
    val uiState = _uiState.asStateFlow()

    fun onMenuChange(newValue: String) {
        _uiState.update { it.copy(menu = newValue) }
    }

    fun onProteinChange(newValue: String) {
        _uiState.update { it.copy(protein = newValue) }
    }

    fun onLemakChange(newValue: String) {
        _uiState.update { it.copy(lemak = newValue) }
    }

    fun onKarbohidratChange(newValue: String) {
        _uiState.update { it.copy(karbohidrat = newValue) }
    }

    fun addMenu() {
        val state = _uiState.value
        val protein = state.protein.toDoubleOrNull() ?: 0.0
        val lemak = state.lemak.toDoubleOrNull() ?: 0.0
        val karbo = state.karbohidrat.toDoubleOrNull() ?: 0.0

        // Calculate calories: (protein * 4) + (carbs * 4) + (fat * 9)
        val kkal = ((protein * 4) + (karbo * 4) + (lemak * 9)).toInt()

        val newFoodItem = FoodItem(
            id = 0, // ID will be generated by the repository
            name = state.menu,
            kkal = kkal,
            protein = protein,
            lemak = lemak,
            karbo = karbo
        )
        viewModelScope.launch {
            repository.addFoodItem(newFoodItem)
        }
    }
}